### ISSUE TITLE
libhoard.so: undefined reference to `HL::__errno_location()

### ISSUE THREAD

**Issue by olzhabay** [SudarsunKannan/lsm_nvm#3]
When compiling, getting this error:
```
libhoard.so: undefined reference to `HL::__errno_location()
```
I have changed a line where hoard wrapper defines ramdisk location in `hoard/heaplayers/wrappers/mmapwrapper.h`

Any solution how to fix that?

**Comment by sudarsunkannan** [comment]
Do you get the issue after the following commands? 

  $ cd hoard
  $ ./compile_install_hoard.sh

**Comment by olzhabay** [comment]
There was some linking error from my side, and now this issue is fixed.
However, there are other issues exists, which I emailed you.
